-- Archivo de configuración inicial para la base de datos MySQL (database.sql)
-- Puedes importarlo en tu gestor (PhpMyAdmin, DBeaver, MySQL Workbench, etc.)

CREATE DATABASE IF NOT EXISTS `employees_db`
  CHARACTER SET = 'utf8mb4'
  COLLATE = 'utf8mb4_unicode_ci';

USE `employees_db`;

CREATE TABLE IF NOT EXISTS `employees` (
    `id` INT AUTO_INCREMENT PRIMARY KEY,
    `nombre` VARCHAR(255) NOT NULL,
    `email` VARCHAR(255) NOT NULL UNIQUE,
    `cargo` VARCHAR(255) NOT NULL,
    `departamento` VARCHAR(255) NOT NULL,
    `salario` DECIMAL(10, 2) NOT NULL,
    `is_active` TINYINT(1) DEFAULT 1,
    INDEX `ix_employees_email` (`email`),
    INDEX `ix_employees_nombre` (`nombre`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- (Opcional) Insertar empleados de prueba
INSERT INTO `employees` (`nombre`, `email`, `cargo`, `departamento`, `salario`, `is_active`) VALUES
('Laura Martínez', 'laura.martinez1@empresa.com', 'Desarrollador Backend', 'Calidad', 4236.26, 0),
('Luisa López', 'luisa.lopez2@empresa.com', 'Analista de Datos', 'Data', 4478.85, 0),
('Carlos Romero', 'carlos.romero3@empresa.com', 'DevOps Engineer', 'Diseño', 4160.43, 1),
('Valentina Moreno', 'valentina.moreno4@empresa.com', 'Diseñador UX', 'Ingeniería', 4363.06, 0),
('Carlos Navarro', 'carlos.navarro5@empresa.com', 'Soporte Técnico', 'Data', 3955.58, 1),
('Jorge Castro', 'jorge.castro6@empresa.com', 'Scrum Master', 'Calidad', 2476.76, 0),
('Carolina López', 'carolina.lopez7@empresa.com', 'QA Engineer', 'Ingeniería', 3618.79, 1),
('Miguel Rodríguez', 'miguel.rodriguez8@empresa.com', 'Project Manager', 'Soporte', 4217.56, 1),
('Paula Ortiz', 'paula.ortiz9@empresa.com', 'Diseñador UX', 'Ingeniería', 4826.9, 0),
('Valentina Romero', 'valentina.romero10@empresa.com', 'Desarrollador Frontend', 'Gestión', 2633.65, 1),
('Luisa Gómez', 'luisa.gomez11@empresa.com', 'QA Engineer', 'Calidad', 4471.57, 0),
('Juan Castro', 'juan.castro12@empresa.com', 'Desarrollador Frontend', 'Ingeniería', 3090.34, 0),
('Ana Hernández', 'ana.hernandez13@empresa.com', 'Scrum Master', 'Data', 3561.83, 0),
('Carolina Vargas', 'carolina.vargas14@empresa.com', 'DevOps Engineer', 'Infraestructura', 3770.05, 1),
('Andrés Torres', 'andres.torres15@empresa.com', 'Desarrollador Backend', 'Ingeniería', 2314.89, 1),
('Natalia Silva', 'natalia.silva16@empresa.com', 'Soporte Técnico', 'Infraestructura', 4133.29, 1),
('Jorge Romero', 'jorge.romero17@empresa.com', 'Desarrollador Frontend', 'Calidad', 2354.71, 1),
('Luisa Silva', 'luisa.silva18@empresa.com', 'Diseñador UX', 'Soporte', 2692.58, 0),
('Luisa Pérez', 'luisa.perez19@empresa.com', 'QA Engineer', 'Soporte', 2851.66, 1),
('Luis López', 'luis.lopez20@empresa.com', 'Desarrollador Backend', 'Infraestructura', 4791.99, 0),
('Paula Navarro', 'paula.navarro21@empresa.com', 'Project Manager', 'Infraestructura', 2704.82, 0),
('Valentina Torres', 'valentina.torres22@empresa.com', 'Analista de Datos', 'Data', 4385.19, 0),
('Luisa Silva', 'luisa.silva23@empresa.com', 'Project Manager', 'Gestión', 3983.5, 0),
('David Suárez', 'david.suarez24@empresa.com', 'Administrador BD', 'Ingeniería', 2865.07, 1),
('Sebastián Castro', 'sebastian.castro25@empresa.com', 'Scrum Master', 'Gestión', 2603.0, 0),
('Andrea Gómez', 'andrea.gomez26@empresa.com', 'Soporte Técnico', 'Infraestructura', 2780.03, 0),
('Juan García', 'juan.garcia27@empresa.com', 'QA Engineer', 'Ingeniería', 2399.69, 0),
('Andrea Romero', 'andrea.romero28@empresa.com', 'Desarrollador Backend', 'Soporte', 4618.05, 0),
('Felipe Silva', 'felipe.silva29@empresa.com', 'Soporte Técnico', 'Calidad', 3635.57, 0),
('Camilo Vargas', 'camilo.vargas30@empresa.com', 'Desarrollador Frontend', 'Data', 3083.54, 1),
('Diana Silva', 'diana.silva31@empresa.com', 'Administrador BD', 'Gestión', 4117.25, 1),
('Laura Rodríguez', 'laura.rodriguez32@empresa.com', 'Desarrollador Frontend', 'Calidad', 3431.83, 1),
('Luis Vargas', 'luis.vargas33@empresa.com', 'Diseñador UX', 'Infraestructura', 4582.75, 1),
('Carolina Castro', 'carolina.castro34@empresa.com', 'Scrum Master', 'Calidad', 4498.64, 1),
('Miguel Ortiz', 'miguel.ortiz35@empresa.com', 'DevOps Engineer', 'Soporte', 4406.66, 1),
('Camilo Gómez', 'camilo.gomez36@empresa.com', 'Desarrollador Frontend', 'Soporte', 2197.1, 1),
('Valentina Romero', 'valentina.romero37@empresa.com', 'Analista de Datos', 'Soporte', 4046.91, 0),
('Carolina Castaño', 'carolina.castano38@empresa.com', 'QA Engineer', 'Infraestructura', 2856.83, 0),
('David Ramírez', 'david.ramirez39@empresa.com', 'QA Engineer', 'Calidad', 4743.83, 0),
('Carlos Torres', 'carlos.torres40@empresa.com', 'DevOps Engineer', 'Data', 2862.38, 1),
('Laura Gómez', 'laura.gomez41@empresa.com', 'Project Manager', 'Gestión', 2429.39, 0),
('Jorge García', 'jorge.garcia42@empresa.com', 'Scrum Master', 'Infraestructura', 3752.29, 0),
('Jorge Moreno', 'jorge.moreno43@empresa.com', 'QA Engineer', 'Ingeniería', 2891.68, 1),
('Sebastián Martínez', 'sebastian.martinez44@empresa.com', 'DevOps Engineer', 'Ingeniería', 2052.91, 0),
('Andrés Suárez', 'andres.suarez45@empresa.com', 'Soporte Técnico', 'Calidad', 2537.74, 0),
('Andrés Ortiz', 'andres.ortiz46@empresa.com', 'Project Manager', 'Calidad', 4366.9, 0),
('Diana Hernández', 'diana.hernandez47@empresa.com', 'Desarrollador Frontend', 'Calidad', 3090.08, 0),
('David López', 'david.lopez48@empresa.com', 'Project Manager', 'Infraestructura', 2511.88, 0),
('Andrés Suárez', 'andres.suarez49@empresa.com', 'Desarrollador Backend', 'Ingeniería', 3105.52, 1),
('Carlos García', 'carlos.garcia50@empresa.com', 'Desarrollador Backend', 'Data', 4415.71, 1),
('Valentina Moreno', 'valentina.moreno51@empresa.com', 'Analista de Datos', 'Ingeniería', 3342.47, 1),
('María Martínez', 'maria.martinez52@empresa.com', 'QA Engineer', 'Calidad', 3873.19, 0),
('Laura Castaño', 'laura.castano53@empresa.com', 'Soporte Técnico', 'Data', 4909.54, 1),
('Laura García', 'laura.garcia54@empresa.com', 'QA Engineer', 'Soporte', 3499.3, 1),
('Camilo Rojas', 'camilo.rojas55@empresa.com', 'DevOps Engineer', 'Infraestructura', 3715.68, 0),
('Natalia Hernández', 'natalia.hernandez56@empresa.com', 'Administrador BD', 'Calidad', 4601.06, 0),
('Luisa Ortiz', 'luisa.ortiz57@empresa.com', 'Administrador BD', 'Gestión', 4038.94, 0),
('Valentina Vargas', 'valentina.vargas58@empresa.com', 'Desarrollador Backend', 'Data', 3307.55, 0),
('Diana Ramírez', 'diana.ramirez59@empresa.com', 'Diseñador UX', 'Soporte', 3190.01, 1),
('Camilo Romero', 'camilo.romero60@empresa.com', 'QA Engineer', 'Ingeniería', 2252.32, 1),
('David Ortiz', 'david.ortiz61@empresa.com', 'Desarrollador Frontend', 'Data', 2352.98, 0),
('Carolina Silva', 'carolina.silva62@empresa.com', 'DevOps Engineer', 'Gestión', 4544.38, 0),
('Luis Hernández', 'luis.hernandez63@empresa.com', 'Desarrollador Frontend', 'Ingeniería', 4829.18, 1),
('Andrea Rojas', 'andrea.rojas64@empresa.com', 'Analista de Datos', 'Ingeniería', 2012.05, 0),
('Luisa Castaño', 'luisa.castano65@empresa.com', 'Administrador BD', 'Ingeniería', 3631.06, 1),
('David Navarro', 'david.navarro66@empresa.com', 'Scrum Master', 'Infraestructura', 4366.85, 1),
('Luis Rojas', 'luis.rojas67@empresa.com', 'Desarrollador Frontend', 'Gestión', 2517.01, 0),
('Natalia Gómez', 'natalia.gomez68@empresa.com', 'Analista de Datos', 'Data', 2942.18, 0),
('Sebastián Castaño', 'sebastian.castano69@empresa.com', 'QA Engineer', 'Ingeniería', 2159.29, 1),
('David Martínez', 'david.martinez70@empresa.com', 'Desarrollador Backend', 'Diseño', 4724.03, 1),
('Paula Gómez', 'paula.gomez71@empresa.com', 'Diseñador UX', 'Infraestructura', 4333.37, 0),
('Carlos López', 'carlos.lopez72@empresa.com', 'Desarrollador Frontend', 'Infraestructura', 3848.56, 1),
('Felipe Castro', 'felipe.castro73@empresa.com', 'QA Engineer', 'Diseño', 2148.33, 1),
('Paula Gómez', 'paula.gomez74@empresa.com', 'DevOps Engineer', 'Calidad', 2749.15, 1),
('Sebastián García', 'sebastian.garcia75@empresa.com', 'DevOps Engineer', 'Infraestructura', 4187.78, 0),
('Valentina Silva', 'valentina.silva76@empresa.com', 'QA Engineer', 'Data', 4179.2, 0),
('Camilo Hernández', 'camilo.hernandez77@empresa.com', 'Scrum Master', 'Gestión', 3588.6, 0),
('Carlos Rodríguez', 'carlos.rodriguez78@empresa.com', 'Desarrollador Backend', 'Soporte', 3565.28, 1),
('Carolina López', 'carolina.lopez79@empresa.com', 'Diseñador UX', 'Infraestructura', 3559.65, 1),
('Luis Ramírez', 'luis.ramirez80@empresa.com', 'QA Engineer', 'Infraestructura', 4564.61, 0),
('Ana Ortiz', 'ana.ortiz81@empresa.com', 'Scrum Master', 'Ingeniería', 4172.41, 0),
('Juan Romero', 'juan.romero82@empresa.com', 'DevOps Engineer', 'Soporte', 4348.07, 1),
('Sebastián Castro', 'sebastian.castro83@empresa.com', 'Project Manager', 'Calidad', 2630.75, 1),
('Andrés López', 'andres.lopez84@empresa.com', 'DevOps Engineer', 'Gestión', 4578.91, 0),
('Sebastián Rodríguez', 'sebastian.rodriguez85@empresa.com', 'Diseñador UX', 'Data', 3589.58, 0),
('Luisa Romero', 'luisa.romero86@empresa.com', 'Project Manager', 'Data', 4386.52, 1),
('Luis Torres', 'luis.torres87@empresa.com', 'Soporte Técnico', 'Data', 2403.4, 1),
('Jorge Romero', 'jorge.romero88@empresa.com', 'Project Manager', 'Diseño', 3615.8, 1),
('Luisa Rojas', 'luisa.rojas89@empresa.com', 'Analista de Datos', 'Diseño', 3642.86, 1),
('Juan Gómez', 'juan.gomez90@empresa.com', 'Soporte Técnico', 'Data', 4906.28, 0),
('David Castaño', 'david.castano91@empresa.com', 'Analista de Datos', 'Soporte', 3322.08, 1),
('Carolina Torres', 'carolina.torres92@empresa.com', 'Analista de Datos', 'Gestión', 2633.54, 1),
('Carlos Navarro', 'carlos.navarro93@empresa.com', 'Analista de Datos', 'Gestión', 4656.05, 0),
('David Castaño', 'david.castano94@empresa.com', 'Soporte Técnico', 'Infraestructura', 3385.18, 1),
('Andrés Silva', 'andres.silva95@empresa.com', 'Desarrollador Frontend', 'Ingeniería', 2773.03, 0),
('Diana Navarro', 'diana.navarro96@empresa.com', 'Project Manager', 'Diseño', 3344.5, 1),
('Carlos Rojas', 'carlos.rojas97@empresa.com', 'Soporte Técnico', 'Diseño', 2443.36, 0),
('Laura Ortiz', 'laura.ortiz98@empresa.com', 'Scrum Master', 'Data', 4082.32, 0),
('Luis Romero', 'luis.romero99@empresa.com', 'Soporte Técnico', 'Gestión', 3120.22, 0),
('Carolina Ramírez', 'carolina.ramirez100@empresa.com', 'Administrador BD', 'Ingeniería', 2305.4, 1),
('Diana Suárez', 'diana.suarez101@empresa.com', 'QA Engineer', 'Soporte', 4625.77, 0),
('Carlos Castro', 'carlos.castro102@empresa.com', 'Desarrollador Backend', 'Diseño', 3049.09, 0),
('Laura Gómez', 'laura.gomez103@empresa.com', 'Analista de Datos', 'Infraestructura', 4270.07, 0),
('Andrea Rodríguez', 'andrea.rodriguez104@empresa.com', 'Project Manager', 'Infraestructura', 4439.8, 1),
('Carlos Vargas', 'carlos.vargas105@empresa.com', 'Scrum Master', 'Diseño', 2542.7, 1),
('Andrés Silva', 'andres.silva106@empresa.com', 'QA Engineer', 'Ingeniería', 4894.84, 1),
('Felipe Rodríguez', 'felipe.rodriguez107@empresa.com', 'DevOps Engineer', 'Ingeniería', 4143.62, 0),
('Andrés Romero', 'andres.romero108@empresa.com', 'Analista de Datos', 'Diseño', 3211.58, 1),
('Juan López', 'juan.lopez109@empresa.com', 'Desarrollador Backend', 'Ingeniería', 3026.27, 0),
('Ana Pérez', 'ana.perez110@empresa.com', 'Scrum Master', 'Diseño', 4535.17, 0),
('Luisa Navarro', 'luisa.navarro111@empresa.com', 'Desarrollador Backend', 'Ingeniería', 2213.27, 1),
('Andrea Gómez', 'andrea.gomez112@empresa.com', 'Scrum Master', 'Calidad', 2015.72, 0),
('Paula Ramírez', 'paula.ramirez113@empresa.com', 'Desarrollador Backend', 'Ingeniería', 3993.62, 1),
('Camilo Castro', 'camilo.castro114@empresa.com', 'Administrador BD', 'Gestión', 4039.14, 0),
('David Suárez', 'david.suarez115@empresa.com', 'Scrum Master', 'Soporte', 4516.23, 1),
('Laura Rodríguez', 'laura.rodriguez116@empresa.com', 'Administrador BD', 'Gestión', 2281.84, 1),
('María Gómez', 'maria.gomez117@empresa.com', 'Soporte Técnico', 'Data', 4021.92, 1),
('Camilo Torres', 'camilo.torres118@empresa.com', 'Administrador BD', 'Diseño', 2665.1, 0),
('Carolina Gómez', 'carolina.gomez119@empresa.com', 'Analista de Datos', 'Calidad', 4920.68, 0),
('David Gómez', 'david.gomez120@empresa.com', 'Soporte Técnico', 'Soporte', 2967.82, 0),
('Paula Mendoza', 'paula.mendoza121@empresa.com', 'Desarrollador Frontend', 'Diseño', 4801.4, 0),
('Andrés López', 'andres.lopez122@empresa.com', 'Project Manager', 'Diseño', 3031.76, 1),
('Felipe Vargas', 'felipe.vargas123@empresa.com', 'Desarrollador Frontend', 'Data', 2060.77, 0),
('Camilo Torres', 'camilo.torres124@empresa.com', 'Soporte Técnico', 'Infraestructura', 2301.18, 0),
('Luisa Pérez', 'luisa.perez125@empresa.com', 'QA Engineer', 'Ingeniería', 2439.82, 1),
('Andrea Mendoza', 'andrea.mendoza126@empresa.com', 'Desarrollador Backend', 'Data', 3670.19, 0),
('Natalia Moreno', 'natalia.moreno127@empresa.com', 'Project Manager', 'Data', 3716.57, 1),
('Diana Silva', 'diana.silva128@empresa.com', 'Project Manager', 'Data', 4616.78, 0),
('Diana Castro', 'diana.castro129@empresa.com', 'Diseñador UX', 'Data', 2702.59, 0),
('Jorge Rojas', 'jorge.rojas130@empresa.com', 'Diseñador UX', 'Infraestructura', 3986.68, 1),
('Laura Pérez', 'laura.perez131@empresa.com', 'Analista de Datos', 'Calidad', 3890.71, 0),
('Juan Suárez', 'juan.suarez132@empresa.com', 'Desarrollador Backend', 'Gestión', 3903.69, 0),
('Camilo Rodríguez', 'camilo.rodriguez133@empresa.com', 'Diseñador UX', 'Diseño', 3476.7, 0),
('Valentina Ramírez', 'valentina.ramirez134@empresa.com', 'Administrador BD', 'Diseño', 2502.11, 0),
('Andrés Pérez', 'andres.perez135@empresa.com', 'Scrum Master', 'Ingeniería', 2173.74, 0),
('Felipe García', 'felipe.garcia136@empresa.com', 'Scrum Master', 'Gestión', 3288.28, 1),
('Carolina Martínez', 'carolina.martinez137@empresa.com', 'Scrum Master', 'Infraestructura', 3732.85, 0),
('Ana Gómez', 'ana.gomez138@empresa.com', 'Diseñador UX', 'Gestión', 4334.81, 1),
('Valentina Pérez', 'valentina.perez139@empresa.com', 'QA Engineer', 'Calidad', 3748.71, 0),
('Diana Moreno', 'diana.moreno140@empresa.com', 'DevOps Engineer', 'Data', 4586.91, 1),
('David Rodríguez', 'david.rodriguez141@empresa.com', 'DevOps Engineer', 'Diseño', 3185.42, 1),
('Diana Silva', 'diana.silva142@empresa.com', 'DevOps Engineer', 'Soporte', 2894.33, 1),
('Juan Torres', 'juan.torres143@empresa.com', 'Desarrollador Frontend', 'Data', 3169.26, 0),
('Miguel Romero', 'miguel.romero144@empresa.com', 'Soporte Técnico', 'Data', 3377.08, 0),
('Ana Romero', 'ana.romero145@empresa.com', 'Project Manager', 'Calidad', 2256.12, 0),
('Valentina Castaño', 'valentina.castano146@empresa.com', 'Project Manager', 'Data', 3414.11, 0),
('Felipe García', 'felipe.garcia147@empresa.com', 'Scrum Master', 'Ingeniería', 4085.52, 1),
('Camilo Martínez', 'camilo.martinez148@empresa.com', 'Analista de Datos', 'Gestión', 2383.03, 0),
('Luis Ramírez', 'luis.ramirez149@empresa.com', 'Desarrollador Frontend', 'Soporte', 2127.81, 1),
('Andrés Torres', 'andres.torres150@empresa.com', 'Soporte Técnico', 'Diseño', 4792.64, 1),
('Camilo Navarro', 'camilo.navarro151@empresa.com', 'Project Manager', 'Ingeniería', 3147.95, 1),
('Andrea Torres', 'andrea.torres152@empresa.com', 'Soporte Técnico', 'Infraestructura', 2296.94, 0),
('Luisa Pérez', 'luisa.perez153@empresa.com', 'Analista de Datos', 'Infraestructura', 3457.97, 0),
('Luisa Suárez', 'luisa.suarez154@empresa.com', 'Administrador BD', 'Calidad', 3434.81, 1),
('Camilo García', 'camilo.garcia155@empresa.com', 'Desarrollador Backend', 'Calidad', 4946.96, 0),
('Luis Silva', 'luis.silva156@empresa.com', 'Desarrollador Frontend', 'Calidad', 2804.24, 1),
('Valentina Gómez', 'valentina.gomez157@empresa.com', 'Desarrollador Frontend', 'Soporte', 3392.87, 0),
('Laura Moreno', 'laura.moreno158@empresa.com', 'QA Engineer', 'Data', 2591.02, 0),
('Sebastián Mendoza', 'sebastian.mendoza159@empresa.com', 'Soporte Técnico', 'Calidad', 3291.94, 0),
('Valentina Suárez', 'valentina.suarez160@empresa.com', 'Desarrollador Backend', 'Soporte', 4152.15, 1),
('Ana Pérez', 'ana.perez161@empresa.com', 'Project Manager', 'Gestión', 2674.37, 0),
('Sebastián García', 'sebastian.garcia162@empresa.com', 'Administrador BD', 'Gestión', 4132.46, 0),
('Laura Ramírez', 'laura.ramirez163@empresa.com', 'DevOps Engineer', 'Calidad', 3534.59, 1),
('David Silva', 'david.silva164@empresa.com', 'Project Manager', 'Soporte', 2050.76, 0),
('Luis Ortiz', 'luis.ortiz165@empresa.com', 'Desarrollador Backend', 'Diseño', 3739.64, 0),
('Andrea Ortiz', 'andrea.ortiz166@empresa.com', 'Desarrollador Backend', 'Soporte', 3242.04, 1),
('Carlos Mendoza', 'carlos.mendoza167@empresa.com', 'Scrum Master', 'Ingeniería', 4156.75, 1),
('Valentina Vargas', 'valentina.vargas168@empresa.com', 'Diseñador UX', 'Data', 2576.67, 0),
('Andrea Torres', 'andrea.torres169@empresa.com', 'Soporte Técnico', 'Gestión', 3454.71, 1),
('Carlos Moreno', 'carlos.moreno170@empresa.com', 'Desarrollador Backend', 'Soporte', 3604.0, 0),
('David Mendoza', 'david.mendoza171@empresa.com', 'Scrum Master', 'Gestión', 4517.56, 0),
('Juan Martínez', 'juan.martinez172@empresa.com', 'Diseñador UX', 'Infraestructura', 2612.32, 0),
('Luisa García', 'luisa.garcia173@empresa.com', 'Scrum Master', 'Calidad', 3705.61, 0),
('Andrea Hernández', 'andrea.hernandez174@empresa.com', 'Analista de Datos', 'Diseño', 4100.87, 0),
('Valentina Castaño', 'valentina.castano175@empresa.com', 'Desarrollador Frontend', 'Diseño', 4747.56, 0),
('Sebastián Gómez', 'sebastian.gomez176@empresa.com', 'Soporte Técnico', 'Gestión', 3888.79, 0),
('Valentina Hernández', 'valentina.hernandez177@empresa.com', 'Analista de Datos', 'Diseño', 3242.96, 1),
('Sebastián Vargas', 'sebastian.vargas178@empresa.com', 'Soporte Técnico', 'Calidad', 3398.61, 1),
('Miguel Pérez', 'miguel.perez179@empresa.com', 'Analista de Datos', 'Ingeniería', 4402.55, 1),
('Natalia Ramírez', 'natalia.ramirez180@empresa.com', 'Desarrollador Backend', 'Infraestructura', 4921.44, 0),
('David Moreno', 'david.moreno181@empresa.com', 'Scrum Master', 'Diseño', 4682.39, 0),
('Natalia Silva', 'natalia.silva182@empresa.com', 'Analista de Datos', 'Ingeniería', 2827.59, 1),
('María Rodríguez', 'maria.rodriguez183@empresa.com', 'QA Engineer', 'Infraestructura', 2571.64, 1),
('Jorge Vargas', 'jorge.vargas184@empresa.com', 'Project Manager', 'Gestión', 2306.5, 1),
('Natalia Castro', 'natalia.castro185@empresa.com', 'Analista de Datos', 'Data', 3620.4, 1),
('Laura López', 'laura.lopez186@empresa.com', 'Analista de Datos', 'Diseño', 3057.31, 1),
('Jorge Romero', 'jorge.romero187@empresa.com', 'QA Engineer', 'Gestión', 2309.12, 0),
('Felipe Castro', 'felipe.castro188@empresa.com', 'Desarrollador Frontend', 'Gestión', 3672.79, 1),
('Carlos Ramírez', 'carlos.ramirez189@empresa.com', 'Desarrollador Backend', 'Ingeniería', 3012.84, 0),
('Luis Ramírez', 'luis.ramirez190@empresa.com', 'Analista de Datos', 'Infraestructura', 3600.49, 0),
('Camilo López', 'camilo.lopez191@empresa.com', 'QA Engineer', 'Infraestructura', 4494.12, 0),
('Miguel Ortiz', 'miguel.ortiz192@empresa.com', 'Desarrollador Frontend', 'Diseño', 3181.5, 0),
('Sebastián Vargas', 'sebastian.vargas193@empresa.com', 'Diseñador UX', 'Infraestructura', 3456.0, 1),
('Jorge Vargas', 'jorge.vargas194@empresa.com', 'Diseñador UX', 'Calidad', 4594.07, 0),
('Andrés Suárez', 'andres.suarez195@empresa.com', 'Desarrollador Frontend', 'Calidad', 3463.8, 1),
('Sebastián Hernández', 'sebastian.hernandez196@empresa.com', 'Soporte Técnico', 'Infraestructura', 4363.06, 1),
('Andrés Suárez', 'andres.suarez197@empresa.com', 'QA Engineer', 'Data', 2048.89, 0),
('Luisa Martínez', 'luisa.martinez198@empresa.com', 'Soporte Técnico', 'Calidad', 2456.1, 1),
('Laura Suárez', 'laura.suarez199@empresa.com', 'Analista de Datos', 'Diseño', 4648.08, 0),
('Diana Mendoza', 'diana.mendoza200@empresa.com', 'QA Engineer', 'Infraestructura', 4329.01, 1);